// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZaalvoetbalService.Data;

#nullable disable

namespace ZaalvoetbalService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629074051_AanpassingenInDatabase")]
    partial class AanpassingenInDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZaalvoetbalService.Models.Doelpunt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("Ploeg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpelerNaam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Doelpunten");
                });

            modelBuilder.Entity("ZaalvoetbalService.Models.Kaart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Kleur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("Ploeg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpelerNaam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Kaarten");
                });

            modelBuilder.Entity("ZaalvoetbalService.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Datum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thuisploeg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThuisploegScore")
                        .HasColumnType("int");

                    b.Property<string>("Uitploeg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UitploegScore")
                        .HasColumnType("int");

                    b.Property<string>("Uur")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Matchen");
                });

            modelBuilder.Entity("ZaalvoetbalService.Models.Ploeg", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ploegen");
                });

            modelBuilder.Entity("ZaalvoetbalService.Models.Speler", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PloegId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("PloegId");

                    b.ToTable("Spelers");
                });

            modelBuilder.Entity("ZaalvoetbalService.Models.Stem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<string>("Ploeg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpelerNaam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("Stemmen");
                });

            modelBuilder.Entity("ZaalvoetbalService.Models.Doelpunt", b =>
                {
                    b.HasOne("ZaalvoetbalService.Models.Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("ZaalvoetbalService.Models.Kaart", b =>
                {
                    b.HasOne("ZaalvoetbalService.Models.Match", "Match")
                        .WithMany("Kaarten")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("ZaalvoetbalService.Models.Speler", b =>
                {
                    b.HasOne("ZaalvoetbalService.Models.Match", null)
                        .WithMany("Doelpuntenmakers")
                        .HasForeignKey("MatchId");

                    b.HasOne("ZaalvoetbalService.Models.Ploeg", "Ploeg")
                        .WithMany("Spelers")
                        .HasForeignKey("PloegId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ploeg");
                });

            modelBuilder.Entity("ZaalvoetbalService.Models.Stem", b =>
                {
                    b.HasOne("ZaalvoetbalService.Models.Match", "Match")
                        .WithMany("Stemmen")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("ZaalvoetbalService.Models.Match", b =>
                {
                    b.Navigation("Doelpuntenmakers");

                    b.Navigation("Kaarten");

                    b.Navigation("Stemmen");
                });

            modelBuilder.Entity("ZaalvoetbalService.Models.Ploeg", b =>
                {
                    b.Navigation("Spelers");
                });
#pragma warning restore 612, 618
        }
    }
}
